# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Github/MotionDetection/FPGA/motion_detection.srcs/sources_1/ip/InputFrames/InputFrames.xci
# IP: The module: 'InputFrames' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Github/MotionDetection/FPGA/motion_detection.srcs/sources_1/ip/InputFrames/InputFrames_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'InputFrames'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Github/MotionDetection/FPGA/motion_detection.srcs/sources_1/ip/InputFrames/InputFrames.xci
# IP: The module: 'InputFrames' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Github/MotionDetection/FPGA/motion_detection.srcs/sources_1/ip/InputFrames/InputFrames_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'InputFrames'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
