# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/programming/GitHub/MotionDetection/FPGA2/FPGA2.srcs/sources_1/ip/ref_image_RAM/ref_image_RAM.xci
# IP: The module: 'ref_image_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/programming/GitHub/MotionDetection/FPGA2/FPGA2.srcs/sources_1/ip/ref_image_RAM/ref_image_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ref_image_RAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/programming/GitHub/MotionDetection/FPGA2/FPGA2.srcs/sources_1/ip/ref_image_RAM/ref_image_RAM.xci
# IP: The module: 'ref_image_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/programming/GitHub/MotionDetection/FPGA2/FPGA2.srcs/sources_1/ip/ref_image_RAM/ref_image_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ref_image_RAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
