# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/programming/GitHub/MotionDetection/FPGA/motion_detection.srcs/sources_1/ip/Reference_frame/Reference_frame.xci
# IP: The module: 'Reference_frame' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/programming/GitHub/MotionDetection/FPGA/motion_detection.srcs/sources_1/ip/Reference_frame/Reference_frame_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Reference_frame'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/programming/GitHub/MotionDetection/FPGA/motion_detection.srcs/sources_1/ip/Reference_frame/Reference_frame.xci
# IP: The module: 'Reference_frame' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/programming/GitHub/MotionDetection/FPGA/motion_detection.srcs/sources_1/ip/Reference_frame/Reference_frame_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Reference_frame'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
